use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'LLUPNPServer_Example' do
  pod 'LLUPNPServer', :path => '../'
  target 'LLUPNPServer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
